### PR TITLE
authorize colon & digit

### PR DESCRIPTION
**Pull request by KannarFr**
Fixes https://github.com/CleverCloud/biscuit-java/issues/48

### CODE REVIEW

**Comment by Korbik** [comment]
We should add unit tests because we have missed this case and I would like to avoid at least regretion

**Review by Geal — APPROVED** [review]

**Comment by Geal** [comment]
Agreed, it needs more tests

**Comment by KannarFr** [comment]
@Korbik LGTY?

**Comment by Korbik** [comment]
I have added a test on the parser. Looks good to me.

**Pull request merged**
